version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    executor:
      name: node/default
      tag: "16"
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
