name: Deploy
on:
  push:
    # tags:
    #   - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      # - run: yarn build
      # - run: yarn test
      - run: echo "@rodrigogirao:registry=https://npm.pkg.github.com" > .npmrc
      - run: pwd
      - run: cat package.json
      - run: cat .npmrc
      - run: yarn publish
