name: Build
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > .npmrc
      - run: yarn publish
